source :rubygems

gem 'rake'
gem 'ramaze'
gem 'sequel'
gem 'bacon'
gem 'mysql2'
gem 'json'
gem 'thin'
gem 'unicorn'
gem 'foreman'
gem 'pony'
#gem 'guid'
gem 'bcrypt-ruby'
gem 'redis'
gem 'fnordmetric'
  #:git => 'https://github.com/hewo/fnordmetric.git', :branch => 'master'
gem 'sidekiq'
gem 'slim'
gem 'sprockets'
gem 'daemons'

group :development do
  gem 'rdoc'
  gem 'rdoc-data'
  #gem 'heroku'
  gem 'rspec'
  gem 'bacon'
  gem 'yard'
  gem 'bundler'
  gem 'simplecov'
  gem 'rack-test'
  gem 'nokogiri'
  gem 'lolcommits'
  gem 'sqlite3'
  gem 'capybara'
  #gem 'capybara-screenshot'
  gem 'coveralls', require: false
end
